Repository hibobio/environment-hibob-stage-dev-new-dev, pull requests merged in 2020-05, with the labels that each got.

#18 added jx ui
  env/jx-app-ui/values.yaml
  env/jxboot-resources/values.tmpl.yaml
  env/requirements.yaml
  jx-requirements.yml
  systems/external-dns/values.tmpl.yaml
Labels: size/S

#20 feat(config): upgrade configuration
  bdd/boot-local/jx-requirements.yml
  bdd/boot-vault/jx-requirements.yml
  env/lighthouse/values.tmpl.yaml
  env/values.tmpl.yaml
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
  jx-requirements.yml
  kubeProviders/aks/values.tmpl.yaml
  kubeProviders/eks/templates/jenkinsx-policies.yml
  kubeProviders/eks/values.tmpl.yaml
  kubeProviders/gke/values.tmpl.yaml
  kubeProviders/openshift/values.tmpl.yaml
  systems/acme/Chart.yaml
Labels: size/L

#21 chore(deps): bump https://github.com/hibobio/surveys.git
  repositories/templates/hibobio-surveys-sr.yaml
Labels: size/M, updatebot

#22 chore(deps): bump https://github.com/hibobio/surveys.git
  repositories/templates/hibobio-surveys-sr.yaml
Labels: size/M, updatebot

#23 Remove pazt owners
  OWNERS
  env/jenkins-x-platform/values.tmpl.yaml
Labels: size/XS
